name: Pull Request Checks

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint:check

      - name: Check formatting
        run: yarn format:check

      - name: Generate Prisma client
        run: yarn prisma generate

      - name: Run unit tests
        run: yarn test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          JWT_SECRET: test_jwt_secret
          JWT_EXPIRATION: 3600